### ISSUE TITLE
Cannot see configuration on user account page

### ISSUE THREAD

**Issue by carukc** [MicroHealthLLC/due_date_reminder#1]
Hello,

Thank you for updating this plugin.  It's just what I was looking for.  Unfortunately I cannot see the updated Email Notification configuration on any of the user account pages.

I've installed and migrated and can see the plugin default settings.  The plugin rake send script also seems to work (or at least it runs without errors) but users cannot configure their notification preferences.  The notification configuration text does not appear on their account page.

I'm running:

Environment:
  Redmine version                3.2.3.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.9.2
  Filesystem  
Redmine plugins:
  a_common_libs                  2.1.9
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  due_date_reminder              0.3.2
  easy_baseline                  2014
  easy_gantt_pro                 2016-RC1.0
  extra_queries                  2.0.0
  localizable                    0.4.0
  manage_wiki_view_page_permission 0.0.1
  quick_edit                     0.0.9
  redmine_agile                  1.3.11
  redmine_checklists             3.1.3
  redmine_contacts               4.0.1
  redmine_custom_workflows       0.1.6
  redmine_dmsf                   1.5.6
  redmine_information            1.0.2
  redmine_issue_tabs             1.1.0
  redmine_issues_tree            0.0.7
  redmine_lightbox2              0.2.7
  redmine_mail_handler_clean_body_regexp 0.1
  redmine_my_page_queries        0.1.0
  redmine_per_project_formatting 0.0.4
  redmine_wiki_extensions        0.7.0
  redmine_workflow_hidden_fields 0.3.0

Am I doing something wrong or could there be an incompatibility with something else we are using?

Thanks for the help

**Comment by carukc** [comment]
After a complete restart it appeared under 'Information' rather than 'E-Mail Notifications' as noted in the documentation.  Perhaps this has something to do with Redmine 3.2.3?

Thanks
Chris

**Comment by bluenevus** [comment]
not sure but it should work now in information?  Simply had it updated to work with redmine 3.x
